services:
  app:
    build: .
    container_name: higfxi9k01
    restart: unless-stopped
    ports:
      - "0:80"
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: tesisv1
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./backups:/var/www/html/backups

  mysql:
    image: mysql:8.0
    container_name: higfxi9k01-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tesisv1
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backups:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "3307:3306"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local